"""HTML visualization for debugging analysis results."""

from __future__ import annotations

from hearbeat.models import AnalysisResult


def generate_html(result: AnalysisResult, filename: str = "audio") -> str:
    """Generate a standalone HTML visualization of the analysis.

    Shows:
    - Beat markers
    - Bass event markers
    - Event timeline
    - Statistics
    """
    events = result.events
    duration = result.source.duration_seconds
    bpm = result.rhythm.bpm

    beat_events = [e for e in events if e.type.value == "beat"]
    bass_beat_events = [e for e in events if e.type.value == "bass_beat"]
    bass_offbeat_events = [e for e in events if e.type.value == "bass_offbeat"]
    bass_accent_events = [e for e in events if e.type.value == "bass_accent"]

    def markers_js(evts, color, label, y_offset):
        parts = []
        for e in evts:
            x_pct = (e.time / duration * 100) if duration > 0 else 0
            strength = e.strength
            parts.append(
                f'<div class="marker" style="left:{x_pct:.3f}%;'
                f'background:{color};opacity:{0.4 + 0.6 * strength};'
                f'bottom:{y_offset}px;" '
                f'title="{label} t={e.time:.3f}s str={e.strength:.2f}"></div>'
            )
        return "\n".join(parts)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Hearbeat Analysis: {filename}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: monospace; background: #1a1a2e; color: #e0e0e0; padding: 20px; }}
  h1 {{ color: #00d4ff; margin-bottom: 10px; font-size: 18px; }}
  h2 {{ color: #ff6b6b; margin: 15px 0 8px; font-size: 14px; }}
  .info {{ color: #888; margin-bottom: 20px; font-size: 13px; }}
  .stats {{ display: flex; gap: 20px; flex-wrap: wrap; margin-bottom: 20px; }}
  .stat {{ background: #16213e; padding: 10px 15px; border-radius: 6px; }}
  .stat .label {{ color: #888; font-size: 11px; }}
  .stat .value {{ color: #00d4ff; font-size: 20px; font-weight: bold; }}
  .timeline {{ position: relative; height: 200px; background: #0f3460; border-radius: 8px;
               margin-bottom: 15px; overflow: hidden; }}
  .time-axis {{ position: absolute; bottom: 0; left: 0; right: 0; height: 25px;
                background: rgba(0,0,0,0.3); }}
  .time-label {{ position: absolute; bottom: 5px; color: #666; font-size: 10px;
                 transform: translateX(-50%); }}
  .marker {{ position: absolute; width: 2px; border-radius: 1px; }}
  .marker.beat {{ background: #4ecdc4; height: 8px; bottom: 170px; }}
  .marker.bass-beat {{ background: #ff6b6b; height: 14px; bottom: 140px; }}
  .marker.bass-offbeat {{ background: #ffd93d; height: 10px; bottom: 110px; }}
  .marker.bass-accent {{ background: #ff006e; height: 16px; bottom: 80px; }}
  .legend {{ display: flex; gap: 15px; margin-bottom: 15px; font-size: 12px; }}
  .legend-item {{ display: flex; align-items: center; gap: 5px; }}
  .legend-dot {{ width: 10px; height: 10px; border-radius: 2px; }}
  .waveform {{ height: 60px; background: #16213e; border-radius: 8px; margin-bottom: 15px;
               position: relative; overflow: hidden; }}
  .waveform canvas {{ width: 100%; height: 100%; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 12px; margin-bottom: 20px; }}
  th {{ text-align: left; padding: 6px 10px; background: #16213e; color: #00d4ff; }}
  td {{ padding: 4px 10px; border-bottom: 1px solid #333; }}
  .warnings {{ background: #3d1f00; border: 1px solid #ff6b6b; border-radius: 6px;
               padding: 10px; margin-bottom: 15px; }}
  .warnings li {{ color: #ff6b6b; margin-left: 15px; }}
</style>
</head>
<body>
  <h1>Hearbeat Analysis: {filename}</h1>
  <div class="info">Schema v{result.schema_version} | Generated by hearbeat v0.1.0</div>

  <div class="stats">
    <div class="stat">
      <div class="label">BPM</div>
      <div class="value">{bpm:.2f}</div>
    </div>
    <div class="stat">
      <div class="label">Confidence</div>
      <div class="value">{result.rhythm.confidence:.3f}</div>
    </div>
    <div class="stat">
      <div class="label">Duration</div>
      <div class="value">{duration:.1f}s</div>
    </div>
    <div class="stat">
      <div class="label">Beats</div>
      <div class="value">{result.rhythm.beat_count}</div>
    </div>
    <div class="stat">
      <div class="label">Total Events</div>
      <div class="value">{len(events)}</div>
    </div>
  </div>

  <div class="legend">
    <div class="legend-item"><div class="legend-dot" style="background:#4ecdc4"></div> Beat</div>
    <div class="legend-item"><div class="legend-dot" style="background:#ff6b6b"></div> Bass+Beat</div>
    <div class="legend-item"><div class="legend-dot" style="background:#ffd93d"></div> Bass Offbeat</div>
    <div class="legend-item"><div class="legend-dot" style="background:#ff006e"></div> Bass Accent</div>
  </div>

  <div class="timeline">
    {markers_js(beat_events, '#4ecdc4', 'Beat', 0)}
    {markers_js(bass_beat_events, '#ff6b6b', 'Bass+Beat', 30)}
    {markers_js(bass_offbeat_events, '#ffd93d', 'Bass Offbeat', 60)}
    {markers_js(bass_accent_events, '#ff006e', 'Bass Accent', 90)}
    <div class="time-axis">
"""

    # Add time labels
    num_labels = min(20, max(5, int(duration / 10)))
    for i in range(num_labels + 1):
        t = (duration / num_labels) * i
        x_pct = (t / duration * 100) if duration > 0 else 0
        html += f'      <span class="time-label" style="left:{x_pct:.2f}%">{t:.1f}s</span>\n'

    html += """    </div>
  </div>

  <h2>Bass+Beat Events (on-beat)</h2>
  <table>
    <tr><th>Time</th><th>Strength</th><th>Beat Delta</th><th>Nearest Beat</th><th>Duration</th></tr>
"""
    for e in bass_beat_events:
        html += (
            f'    <tr><td>{e.time:.3f}s</td><td>{e.strength:.3f}</td>'
            f'<td>{e.beat_delta_seconds:+.4f}s</td>'
            f'<td>{e.nearest_beat_time:.3f}s</td>'
            f'<td>{e.duration:.4f}s</td></tr>\n'
        )

    html += """  </table>

  <h2>Bass Offbeat Events</h2>
  <table>
    <tr><th>Time</th><th>Strength</th><th>Beat Delta</th><th>Nearest Beat</th><th>Duration</th></tr>
"""
    for e in bass_offbeat_events:
        html += (
            f'    <tr><td>{e.time:.3f}s</td><td>{e.strength:.3f}</td>'
            f'<td>{e.beat_delta_seconds:+.4f}s</td>'
            f'<td>{e.nearest_beat_time:.3f}s</td>'
            f'<td>{e.duration:.4f}s</td></tr>\n'
        )

    html += """  </table>
"""

    if result.warnings:
        html += '  <h2>Warnings</h2>\n  <div class="warnings"><ul>\n'
        for w in result.warnings:
            html += f"    <li>{w}</li>\n"
        html += "  </ul></div>\n"

    html += """
</body>
</html>"""
    return html
